config/routes.rb
SampleApp::Application.routes.draw do
  
  get "users/new"
  
  
  root  'static_pages#home'
  
  match '/signup',  to: 'users#new',            via: 'get'

  match '/poets', to: 'static_pages#poets', via: 'get'
  
   match '/help',    to: 'static_pages#help',    via: 'get'

  match '/about',   to: 'static_pages#about',   via: 'get'

  match '/contacts', to: 'static_pages#contacts', via: 'get'

  match '/mononoaware', to: 'static_pages#mononoaware', via: 'get'

  match '/pain', to: 'static_pages#pain', via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base

	before_save { self.email = email.downcase }

	validates :name,  presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true,
  	 				  format: { with: VALID_EMAIL_REGEX },
  	 				  uniqueness: { case_sensitive: false }

  	has_secure_password
  	validates :password, length: { minimum: 6 }
  	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    # puts "hello from /home/anthony/rails_projects/sample_app/app/controllers/static_pages_controller.rb"
  end
  
  def help
  end
  
  def about
  end
  
  def contacts
  end

  def poets
  end

  def mononoaware
  end

  def pain
  end

  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
	def full_title(page_title)
	  base_title = "Asheyan"
	  if page_title.empty?
	    base_title
	  else
	    "#{base_title} | #{page_title}"
	  end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contacts_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "sample app", '#', id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",    root_path %></li>
              <li><%= link_to "Pain",    pain_path %></li>
              <li><%= link_to "Слёзы вещей",    mononoaware_path %></li>
              <li><%= link_to "Help",    help_path %></li>
              <li><%= link_to "About Us",    about_path %></li>
              <li><%= link_to "Contacts",    contacts_path %></li>
              <li><%= link_to "Poets",    poets_path %></li>
              <li><%= link_to "Евгений Жаринов",    '#' %></li>
              <li><%= link_to "Аметистовые сады",    '#' %></li>
              <li><%= link_to "Малларме",    '#' %></li>
              <li><%= link_to "Sign in", '#' %></li>
            </ul>
          </nav>
        </div>
      </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <%= render 'layouts/shim' %>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<!-- <!DOCTYPE html>
<html>
  <head>
    <title>Asheyan | <%= yield(:title) %></title>
  </head>
  <body> -->
    <h1>About Us</h1>
    <p>
      Это страничка "Про нас". Этот текст - содержимое тэга "р" внутри тэга воdy.
    </p>
    <p>
      Что можно про нас рассказать? Мы живем на планете Земля - 13 в тентуре.
    </p>
 <!--  </body>
</html> -->

app/views/static_pages/contacts.html.erb
<% provide(:title, 'Contacts') %>
<!-- <!DOCTYPE html>
<html>
  <head>
    <title>Asheyan | <%= yield(:title) %></title>
  </head>
  <body> -->
    <h1>Contacts</h1>
    <p>
      Это страничка "Contacts". По правилам описанным в ~/rails_projects/sample_app/spec/requests/static_pages_spec.rb - страничка должна содержать слово "Contacts" в контенте и также это слово в теге title
    </p>
    <p>
    	оно есть и там, и там - что обеспечивает зеленый в тесте
    </p>
<!--   </body>
</html>
 -->

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<!-- <!DOCTYPE html>
<html>
  <head>
    <title>Asheyan | <%= yield(:title) %></title>
  </head>
  <body> -->
    <h1>Help</h1>
    <p>
      Это страничка "Помощь". Здесь будет расписана структра rails-приложения.
    </p>
    <ul>
    	<li>.bundle</li>
    	<li>______________________________________________________________</li>
    	<li>app
    		<ul>
    			<li>assets
    				<ul>
    					<li>images
    						<ul>
    							<li>logo.png</li>
    							<li>dub.jpg</li>
    						</ul>
    					</li>
    					<!-- <li>javascripts</li> -->
    					<li>stylesheets
    						<ul>
    							<li>custom.css.scss</li>
    						</ul>
    					</li>
    				</ul>
    			</li>
    			<li>controllers
    				<ul>
    					<li>static_pages_controller.rb</li>
    					<li>users_controller.rb</li>
    				</ul>
    			</li>
    			<li>helpers</li>
    			<li>mailers</li>
    			<li>models</li>
    			<li>views
    				<ul>
    					<li>layouts</li>
    					<li>static_pages</li>
    					<li>users</li>
    				</ul>
    			</li>
    		</ul>
    	</li>
    	<li>______________________________________________________________</li>
    	<li>bin</li>
    	<li>______________________________________________________________</li>
    	<li>config
    		<ul>
    			<li>
    				routes.rb
    			</li>
    		</ul>
    	</li>
    	<li>______________________________________________________________</li>
    	<li>db</li>
    	<li>______________________________________________________________</li>
    	<li>lib</li>
    	<li>______________________________________________________________</li>
    	<li>log</li>
    	<li>______________________________________________________________</li>
    	<li>public</li>
    	<li>______________________________________________________________</li>
    	<li>spec</li>
    	<li>______________________________________________________________</li>
    	<li>tmp</li>
    	<li>______________________________________________________________</li>
    	<li>vendor</li>
    	<li>----</li>
    	<li>.gitignore</li>
    	<li>.rspec</li>
    	<li>Gemfile</li>
    	<li>Gemfile.lock</li>
    	<li>README</li>
    	<li>Rakefile</li>
    	<li>config.ru</li>
    </ul>
<!--   </body>
</html> -->

app/views/static_pages/home.html.erb
<!-- <!DOCTYPE html>
<html>
  <head>
    <title>Asheyan | <%= yield(:title) %></title>
  </head>
  <body> -->
  <div class="center hero-unit">
    <p>Find me in app/views/static_pages/home.html.erb</p>

    <p><%=  link_to "Sample App",     "http://polar-waters-4114.herokuapp.com/" %></p>
    <p><%=  link_to "Заводной Мир",   "https://zavodnoy-mir-2596.herokuapp.com/" %></p>
    <p><%=  link_to "February App",   "https://guarded-scrubland-44888.herokuapp.com/" %></p>
    <p><%=  link_to "Bookshop",       "https://floating-falls-74030.herokuapp.com/" %></p>
    

    <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
  </div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>
      
 <!--  </body>
</html> -->

app/views/static_pages/mononoaware.html.erb
<% provide(:title, 'mono no aware') %>

    <h1>Слёзы вещей</h1>
    <p>Lacrimae rerum. Weltschmerz. Mono no aware. </p>
    <p>Печальное очарование вещей. </p>
   	<p>Молчание предметов.</p>

app/views/static_pages/pain.html.erb
<% provide(:title, 'Pain') %>

    <h1>Pain</h1>
    <p>My whole life is a pain</p>
    <p>I'm already dead </p>
   	<p>9</p>

app/views/static_pages/poets.html.erb
<% provide(:title, 'Poets') %>
<!-- <!DOCTYPE html>
<html>
  <head>
    <title>Asheyan | <%= yield(:title) %></title>
  </head>
  <body> -->
    <h1>Poets</h1>
    <p>Это страничка poets.html.erb - она лежит в папке ~sample_app/views/static_pages/poets.html.erb</p>
	<p>в папке же ~/sample_app/spec/requests/static_pages_spec.rb есть описание - что если в тексте страницы poets.html.erb не будет слова Rembo - то при запуске:</p>
	<p>$ bundle exec rspec spec/requests/static_pages_spec.rb</p>
	<p>будет красный fail. Но поскольку слово Rembo - встречается здесь уже второй раз - все в порядке - тест passed. Все green.</p>
  <!-- </body>
</html> -->

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>Find me in app/views/users/new.html.erb</p>